name: 6 - custom role definitions

on:
  #push:
  # branches: 
  #    - main 
  # paths:
  #   - .github/workflows/6-custom-role-definitions.yml
      
  # pull_request:
  #  branches: [ main ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Lint and Build Bicep'
      with:
        inlineScript: |
          az bicep build --file ./eslz/customRoleDefinitions/mgRoleDefinitions.bicep
          az bicep build --file ./eslz/customRoleDefinitions/rgRoleDefinitions.bicep

  validate:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ secrets.AZURE_ENVIRONMENT }}
          enable-AzPSSession: false
        
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}

    - uses: Azure/cli@v1
      name: 'Run preflight validation'
      with:
        inlineScript: |
          az deployment mg validate \
            --name 'Deploy-MG-Custom-Role-Definitions' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/customRoleDefinitions/mgRoleDefinitions.bicep \
            --parameters ./eslz/customRoleDefinitions/.parameters/mgRoleDefinitions.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}
          az deployment sub validate \
            --name 'Deploy-RG-Custom-Role-Definitions' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --template-file ./eslz/customRoleDefinitions/rgRoleDefinitions.bicep \
            --parameters ./eslz/customRoleDefinitions/.parameters/rgRoleDefinitions.json \
            --parameters connSubscriptionId=${{ secrets.AZURE_CONNSUBSCRIPTIONID }}

  preview:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Run what-if'
      with:
        inlineScript: |
          az deployment mg what-if \
            --name 'Deploy-MG-Custom-Role-Definitions' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/customRoleDefinitions/mgRoleDefinitions.bicep \
            --parameters ./eslz/customRoleDefinitions/.parameters/mgRoleDefinitions.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}
          az deployment sub what-if \
            --name 'Deploy-RG-Custom-Role-Definitions' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --template-file ./eslz/customRoleDefinitions/rgRoleDefinitions.bicep \
            --parameters ./eslz/customRoleDefinitions/.parameters/rgRoleDefinitions.json \
            --parameters connSubscriptionId=${{ secrets.AZURE_CONNSUBSCRIPTIONID }}

  deploy:
    runs-on: ubuntu-latest
    needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Deploy - Custom Role Definitions'
      with:
        inlineScript: |
          az deployment mg create \
            --name 'Deploy-MG-Custom-Role-Definitions' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/customRoleDefinitions/mgRoleDefinitions.bicep \
            --parameters ./eslz/customRoleDefinitions/.parameters/mgRoleDefinitions.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}
          az deployment sub create \
            --name 'Deploy-Custom-Role-Definitions' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --template-file ./eslz/customRoleDefinitions/rgRoleDefinitions.bicep \
            --parameters ./eslz/customRoleDefinitions/.parameters/rgRoleDefinitions.json \
            --parameters connSubscriptionId=${{ secrets.AZURE_CONNSUBSCRIPTIONID }}