name: 9 - landing zone policy assignment

on:
  #push:
  # branches: 
  #    - main 
  # paths:
  #   - .github/workflows/9-landing-zone-policy-assignment.yml
      
  # pull_request:
  #  branches: [ main ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Lint and Build Bicep'
      run: az bicep build --file ./eslz/landingZones/policy.assignment.bicep

  validate: 
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ secrets.AZURE_ENVIRONMENT }}
          enable-AzPSSession: false
        
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}

    - uses: Azure/cli@v1
      name: 'Run preflight validation'
      with:
        inlineScript: |
          az deployment mg validate \
            --name 'Landing-Zone-Policy-Assignment' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/landingZones/policy.assignment.bicep \
            --parameters ./eslz/landingZones/.parameters/policy.assignment.parameters.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}

  preview:
      runs-on: ubuntu-latest
      needs: [validate]
      steps:
      - uses: actions/checkout@v2
      
      - uses: azure/login@v1
        name: 'Login to Azure'
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         environment: ${{ secrets.AZURE_ENVIRONMENT }}
         enable-AzPSSession: false
        
      - name: 'Set Azure Subscription'
        run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
                
      - uses: Azure/cli@v1
        name: 'Run what-if'
        with:
          inlineScript: |
            az deployment mg what-if \
            --name 'Landing-Zone-Policy-Assignment' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/landingZones/policy.assignment.bicep \
            --parameters ./eslz/landingZones/.parameters/policy.assignment.parameters.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}


  deploy:
    runs-on: ubuntu-latest
    needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Deploy - Landing Zone Policy Assignment'
      with:
        inlineScript: |
          az deployment mg create \
            --name 'Landing-Zone-Policy-Assignment' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/landingZones/policy.assignment.bicep \
            --parameters ./eslz/landingZones/.parameters/policy.assignment.parameters.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}