name: eslz - sub policy assignment

on:

  push:
   branches: 
      - main 
   paths:
     - .github/workflows/eslz-sub-policy-assignment.yml
      
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Lint and Build Bicep'
      run: az bicep build --file ./eslz/policy/policyAssignments/sub.deploy.bicep

  validate: 
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ secrets.AZURE_ENVIRONMENT }}
          enable-AzPSSession: false
        
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}

    - uses: Azure/cli@v1
      name: 'Run preflight validation'
      with:
        inlineScript: |
            az deployment sub validate \
              --name 'PolicyAssignment-SUB-Scope' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --template-file ./eslz/policy/policyAssignments/sub.deploy.bicep \
              --parameters ./eslz/policy/policyAssignments/.parameters/sub.parameters.json

  preview:
      runs-on: ubuntu-latest
      needs: [validate]
      steps:
      - uses: actions/checkout@v2
      
      - uses: azure/login@v1
        name: 'Login to Azure'
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         environment: ${{ secrets.AZURE_ENVIRONMENT }}
         enable-AzPSSession: false
        
      - name: 'Set Azure Subscription'
        run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
                
      - uses: Azure/cli@v1
        name: 'Run what-if'
        with:
          inlineScript: |
            az deployment sub what-if \
              --name 'PolicyAssignment-SUB-Scope' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --template-file ./eslz/policy/policyAssignments/sub.deploy.bicep \
              --parameters ./eslz/policy/policyAssignments/.parameters/sub.parameters.json

  deploy:
    runs-on: ubuntu-latest
    needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Policy Assignment - Subscription Scope'
      with:
        inlineScript: |
            az deployment sub create \
              --name 'PolicyAssignment-SUB-Scope' \
              --location ${{ secrets.AZURE_LOCATION }} \
              --template-file ./eslz/policy/policyAssignments/sub.deploy.bicep \
              --parameters ./eslz/policy/policyAssignments/.parameters/sub.parameters.json