# This is a basic workflow to help you get started with Actions

name: eslz - management group

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  branches: 
  #    - main 
  #  paths:
  #    - .github/workflows/eslz-management-groups.yml
  #    - eslz/management-groups/*
    
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # "lint" Job ---> will check for ...
  #     (1) syntax errors 
  #     (2) valid Azure resource definitions, and 
  #     (3) code quality.


  deploy:
      runs-on: ubuntu-latest
      environment: Production
      steps:
      - uses: actions/checkout@v2
      
      - uses: azure/login@v1
        name: 'Login to Azure'
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         environment: ${{ secrets.AZURE_ENVIRONMENT }}
         enable-AzPSSession: false
        
      - name: 'Set Azure Subscription'
        run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
                
      - uses: Azure/cli@v1
        name: 'Deploying Management Groups'
        with:
          inlineScript: |
            az deployment tenant create \
              --template-file ./eslz/managementGroups/deploy.bicep \
              --parameters ./eslz/managementGroups/.parameters/parameters.json \
              --parameters ./eslz/managementGroups/.parameters/testmg.parameters.json \
              --location ${{ secrets.AZURE_LOCATION }}
