# This is a basic workflow to help you get started with Actions

name: eslz management group

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
      - main 
      - dev
    paths:
      - entlz-management-groups.yml
      - entlz/management-groups/*
    
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v2
   - name: 'Lint and Build Bicep'
  inputs:
    targetType: filePath
    filePath: $(System.DefaultWorkingDirectory)\entlz\management-groups\build-bicep.ps1

test-deploy:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v2
   - name: 'Test Deployment to Dev Tenant'
  inputs:
    targetType: filePath
    filePath: $(System.DefaultWorkingDirectory)\entlz\management-groups\test-arm.ps1
    arguments: >
      -tenantid $(tenantid) 
      -mgmtsubid $(mgmtsubid) 
      -location $(location) 
      -appid $(appid) 
      -cloudmetadataurl $(cloudmetadataurl) 
      -environment $(environment) 
      -appsecret $(appsecret) 
      -templateparameterfile "build/main.parameters.$(releasetarget).json"
      -templatepath "build/main.json"
      -outfile "build/test-summary-dev.txt"
      
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Deploymentfiles'
  inputs:
    pathToPublish: build
    ArtifactName: drop
    publishLocation: Container
