name: Az Login with OpenID Connect

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 

  build-and-deploy:
    runs-on: ubuntu-latest
    #environment: Production
    steps:
    - name: 'Az Login with OpenID Connect'
      env: 
        GITHUB_BRANCH: ${{ github.ref_name }}
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
          environment: ${{ secrets.AZURE_ENVIRONMENT }}
          
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Azure Cli - List Accounts'
      with:
        inlineScript: |
          az account list -o table