name: Az Login with OpenID Connect

on: 
  workflow_dispatch:

    
jobs: 

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: read
    steps:

    - uses: actions/checkout@v2

    - name: 'Az Login with OpenID Connect'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
          environment: ${{ secrets.AZURE_ENVIRONMENT }}
          
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Azure Cli - List Version'
      with:
        inlineScript: |
          az --version