name: policy comliance scan

on:
  #schedule:
  #  - cron:  '0 8 * * *'  # runs every morning 8am
  
  workflow_dispatch:

jobs:
  login-set-subscription:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - uses: azure/login@v1
      name: 'Login to Azure'
      with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ secrets.AZURE_ENVIRONMENT }}
          enable-AzPSSession: false
        
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}

    - name: 'Assess Policy Compliance'
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/aa2a513a-47e2-4a0d-8d39-0a3d5dd0f889