name: policy comliance scan

on:
  #schedule:
  #  - cron:  '0 8 * * *'  # runs every morning 8am
  
  workflow_dispatch:

jobs:

  azure-policy-compliance-scan:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - uses: azure/login@v1
      name: 'Login to Azure'
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false

    - name: 'Assess Policy Compliance'
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}