name: test - 9 landing zone policy assignment

on:
  #push:
  # branches: 
  #    - main 
  # paths:
  #   - .github/workflows/9-landing-zone-policy-assignment.yml
      
  # pull_request:
  #  branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Deploy - Landing Zone Policy Assignment'
      with:
        inlineScript: |
          az deployment mg create \
            --name 'Landing-Zone-Policy-Assignment' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/landingZones/policy.assignment.bicep \
            --parameters ./eslz/landingZones/.parameters/policy.assignment.parameters.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}