name: test - virtual networking

on:
 push:
  branches: 
     - main 
  paths:
    - .github/workflows/test.vnet.yml
    - test/virtualNetworks/*
    - test/deploy.bicep
      
  # pull_request:
  #  branches: [ main ]
 workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    #needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}

    - uses: Azure/cli@v1
      name: 'Deploy - Platform Hub VNet'
      with:
        inlineScript: |
          az deployment sub create \
            --name 'Deploy-Platform-Hub-VNet' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --template-file ./test/plat.hub.vnet.bicep \
            --parameters ./test/virtualNetworks/.parameters/plat.hub.parameters.json \
            --parameters location=${{ secrets.AZURE_LOCATION }}

    - uses: Azure/cli@v1
      name: 'Deploy - Platform Spoke VNets'
      with:
        inlineScript: |
          az deployment sub create \
            --name 'Deploy-Platform-Spoke-VNets' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --template-file ./test/plat.spoke.vnet.bicep \
            --parameters ./test/virtualNetworks/.parameters/plat.spoke.parameters.json \
            --parameters resourceGroupName=${{ secrets.AZURE_VNETRG }} \
                         location=${{ secrets.AZURE_LOCATION }}