name: test - 6 platform policy assignments

on:
  # push:
  # branches: 
  #    - main 
  # paths:
  #   - .github/workflows/6-platform-policy-assignments.yml
      
  #pull_request:
  #  branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_MGMTSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Platform Policy Assignments'
      with:
        inlineScript: |
          az deployment mg create \
            --name 'Platform-Policy-Assignments' \
            --location ${{ secrets.AZURE_LOCATION }} \
            --management-group-id ${{ secrets.AZURE_MG_TOP }} \
            --template-file ./eslz/policy/policy.assignment.bicep \
            --parameters ./eslz/policy/.parameters/mg.policy.assignment.parameters.json \
            --parameters ./eslz/policy/.parameters/sub.policy.assignment.parameters.json \
            --parameters ./eslz/policy/.parameters/rg.policy.assignment.parameters.json