name: test - virtual networking

on:
 push:
  branches: 
     - main 
  paths:
    - .github/workflows/test.vnet.yml
    - test/virtualNetworks/*
    - test/deploy.bicep
      
  # pull_request:
  #  branches: [ main ]
 workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    #needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}

    - uses: Azure/cli@v1
      name: 'Deploy - Platform-VNets'
      with:
        inlineScript: |
          az deployment group create \
            --name 'Deploy-Platform-VNets' \
            --resource-group ${{ secrets.AZURE_VNETRG }} \
            --template-file ./test/deploy.bicep \
            --parameters ./test/virtualNetworks/.parameters/spoke.parameters.json \
            --parameters resourceGroupName=${{ secrets.AZURE_VNETRG }}