name: test - virtual networking

on:
  push:
   branches: 
      - main 
   paths:
     - .github/workflows/eslz-vnet.yml
      
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    #needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}
              
    - uses: Azure/cli@v1
      name: 'Deploy - Hub-Spoke Networking'
      with:
        inlineScript: |
          az deployment sub create \
            --name 'Deploy-Hub-Spoke-Networking' \
            --template-file ./test/deploy.bicep \
            --parameters ./test/virtualNetworks/.parameters/conn.parameters.json
          az deployment sub create \
            --name 'Deploy-Hub-Spoke-Networking' \
            --template-file ./test/deploy.bicep \
            --parameters ./test/virtualNetworks/.parameters/sand.parameters.json