name: test - load params

on:
  #push:
  # branches: 
  #    - main 
  # paths:
  #   - .github/workflows/test-load-params.yml
      
  # pull_request:
  #  branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    #needs: [preview]
    environment: Production
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      name: 'Login to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: ${{ secrets.AZURE_ENVIRONMENT }}
        enable-AzPSSession: false
      
    - name: 'Set Azure Subscription'
      run: az account set --subscription ${{ secrets.AZURE_CONNSUBSCRIPTIONID }}
    
    - name: Read json
      id: read-json
      shell: pwsh
      run: |
        $params = Get-Content '.\eslz\landingZones\.parameters\parameters.json' | ConvertFrom-Json -Depth 10000
        echo "::set-output name=billingAccount::$(echo $params.parameters.billingAccount.value)"

    - run: echo ${{ steps.read-json.outputs.billingAccount}}