name: test - managementServices

on:
 # push:
 # branches: 
 #    - main 
     
  # pull_request:
  #  branches: [ main ]
 workflow_dispatch:

jobs:

  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Lint and Build Bicep'
      run: az bicep build --file .eslz/managementServices/deploy.bicep

